asynchronous.mail.default.attempt.interval=5000l       // 5 seconds. Dont want mails waiting
//asynchronous.mail.default.max.attempts.count=1
asynchronous.mail.send.repeat.interval=5000l           //  5 seconds. Dont want mails waiting
//asynchronous.mail.expired.collector.repeat.interval=607000l
asynchronous.mail.messages.at.once=100
asynchronous.mail.send.immediately=true  // since 0.1.2
//asynchronous.mail.override=false    // since 0.2.0
//asynchronous.mail.clear.after.sent=false    // since 0.2.0
asynchronous.mail.disable=false    // since 0.7